#include <stdio.h>

void main()
{
    printf("Hello, World!");
    /*
        1. Create a main.c file
        2. Open this file into any IDE (Visual Studio Code).
        3. Write boilerplate code in the main.c file
        4. Open terminal and this this command to compile the main.c file "gcc  main.c".
        5. You see that there is another file that can be generated by compiler a.exe
        6. Now run a.exe file in terminal "./a.exe" and you see the output on the screen.
        7. Additional tip: if you are in VS code so you can install "code runner" extension. it can directly run your code. its advantage is you cannot write "gcc main.c" and a.exe
        if you don't now how to install it go to youtube and search "How to install and use code runner extension in vs code".
        8. And you are good to go.
        9. Happy coding journey.
    */
}